### ISSUE TITLE
Array_doubler incompatible with newest version of codepy (2011.1)?

### ISSUE THREAD

**Issue by sbeamer** [shoaibkamil/asp#2]
After setting up my workspace, my install passes all tests except for array_doubler. The trace is below:
# 
## ERROR: test_generated (**main**.BasicTests)

Traceback (most recent call last):
  File "tests/arraydoubler_test.py", line 13, in test_generated
    result = ArrayDoubler().double_using_template(arr)
  File "/Users/sbeamer/Graphs/special/asp/array_doubler.py", line 16, in double_using_template
    mod.add_function(rendered, fname="double_in_c")
  File "/Users/sbeamer/Graphs/special/asp/asp/jit/asp_module.py", line 113, in add_function
    self.add_function_with_variants(variant_funcs, fname, variant_names, cuda_func=cuda_func)
  File "/Users/sbeamer/Graphs/special/asp/asp/jit/asp_module.py", line 98, in add_function_with_variants
    self.add_function_helper(variant_funcs[x], fname=variant_names[x], cuda_func=cuda_func)
  File "/Users/sbeamer/Graphs/special/asp/asp/jit/asp_module.py", line 82, in add_function_helper
    module.add_function(func)
  File "build/bdist.macosx-10.6-universal/egg/codepy/bpl.py", line 84, in add_function
    func.fdecl.name, func.fdecl.name)))
AttributeError: 'unicode' object has no attribute 'fdecl'

Talking to hcook, he was unable to reproduce the bug. I used easy_install to get codepy, and it seems to have grabbed the latest version (2011.1 which was released on 3/18/11). He is not using this version. Is this update the cause of the bug?

**Comment by sbeamer** [comment]
Shoaib says this is probably caused by Mako moving to unicode by default instead of string.

**Comment by sbeamer** [comment]
What version of Mako should I downgrade to in order to make this go away?

**Comment by sbeamer** [comment]
Made pull request that uses the tweak from the Mako website.

**Comment by shoaibkamil** [comment]
thanks Scott!

**Comment by shoaibkamil** [comment]
This issue looks like it's come back somehow; multiple bug reports now that it is occurring once again.

**Comment by chiaracoetzee** [comment]
Bug is in asp_module, method add_variant(). It does this:

```
    if isinstance(variant_func, str):
        self.backend.module.add_to_module([cpp_ast.Line(variant_func)])
        self.backend.module.add_to_init([cpp_ast.Statement("boost::python::def(\"%s\", &%s)" % (variant_name, variant_name))])
    else:
        self.backend.module.add_function(variant_func)
```

If variant_func is a unicode, it takes the else branch (apparently assuming it's a cgen.FunctionBody).

The isinstance check should be checking for basestring, the superclass of unicode and str, not for str. There are many other isinstance checks in asp_module with the same problem, but changing this one fixed the issue in my case.

**Comment by shoaibkamil** [comment]
FIxed now.
