### ISSUE TITLE
JIT compilation hangs with 'could not acquire lock' messsage

### ISSUE THREAD

**Issue by davidhoward** [shoaibkamil/asp#26]
When the default ASP cache directory (/tmp/asp_cache) is owned by another user, the codepy framework will loop infinitely trying to gain permission to write to it. In order to allow multiple users (or one user ssh'd multiple times) to use ASP at once, per-user cache directories should be created.

offending line in codepy:
codepy/jit.py:350

default cache directory set in ASP:
asp/jit/asp_module.py:302

**Comment by shoaibkamil** [comment]
Fixed by commit 54ca11.
