### ISSUE TITLE
Make internal imports relative

### ISSUE THREAD

**Issue by sbeamer** [shoaibkamil/asp#6]
This is more of a sticky for the upcoming refactoring rather than a bug. To make the asp most usable as a module, all of the import statements referring to asp code should be made relative. Currently they heavily rely on PYTHONPATH.

For the graph specializer I have already started it using asp as a submodule. From the the specializer code, I can refer to the needed asp code by import asp.asp..., but when imported files try to import other asp files, it breaks. Setting PYTHONPATH to the subdirectory where asp is present doesn't fix this because Python checks the same directory as the original import statement (my specializer) before checking PYTHONPATH. It sees asp and thinks it is going to work, but the next word is something like jit or codegen, rather than another asp which is what it needs. My workaround has been to import asp as a submodule named asplib. My code can import it as asplib.asp... and the internal imports work because they fail on the source directory (no asp, just asplib) so it checks PYTHONPATH next.

**Comment by shoaibkamil** [comment]
Added PivotalTracker story for this.

**Comment by sbeamer** [comment]
Sounds like a better place for it.
